Temperature dependence
nu-radio/NuRadioMC pull request #295
Opened 2021-05-17 09:06 UTC by maddalenacat

Issue being addressed:

I added the functions of the Amplifiers temperature dependence in analog_components.py
and I modified HardwareresponseIncorporator that calls analog_components.py that now also contains the temperature as a parameter

2021-05-18 08:21 UTC, christophwelling requested changes
Thanks for implementing this, looks pretty good. I just have a few nitpicks.

2021-05-18 08:21 UTC, christophwelling commented on NuRadioReco/detector/RNO_G/analog_components.py
> +    def get_amp_gain(temp, freqs):
Can you give the temp variable a reasonable default value? That way old code still works if the temperature is not specified.

2021-05-18 08:21 UTC, christophwelling commented on NuRadioReco/modules/RNO_G/hardwareResponseIncorporator.py
> +    def get_filter(self, frequencies, station_id, channel_id, det, temp, sim_to_data=False, phase_only=False, mode=None, mingainlin=None):
Here a default value for temp would also be good.

2021-05-18 08:21 UTC, christophwelling commented on NuRadioReco/detector/RNO_G/analog_components.py
> +    def get_amp_gain(temp, freqs):
Also having temp as the second argument would be better so we don't have to change older code

2021-05-18 08:21 UTC, christophwelling commented on NuRadioReco/modules/RNO_G/hardwareResponseIncorporator.py
> +    def run(self, evt, station, det, temp=20, sim_to_data=False, phase_only=False, mode=None, mingainlin=None):
Can you add a docstring for the temp parameter here as well?

2021-05-18 15:29 UTC, lpyras approved these changes
Thank you for implementing this. Looks good to me.

2021-05-18 19:21 UTC, cg-laser approved these changes
looks also good to me. A bit more documentation would be good though. I think the relevant information is "the function loads a reference measurement made at room temperature and will correct it for the temperature. The correction function was found empirically by studying a few amplifiers in detail in a climate chamber". Or whatever you did. It would also be good if you could add a plot showing the measurement of the temperature dependence, or provide a link to a reference (e.g. RNO-G meeting talk)

2021-06-02 11:45 UTC, cg-laser commented
I just saw now that you edited your initial post. Thanks for adding the documentation! Looks good to me. 
What I also meant that you could add a bit more documentation directly into the source code that explains what the correction function does.

2021-06-02 13:34 UTC, merged