Improve limit plot
nu-radio/NuRadioMC pull request #301
Opened 2021-06-03 12:45 UTC by cg-laser

2021-06-09 15:27 UTC, anelles commented
@clark2668 I saw the ARA 2023 projection, thanks for adding. One question: Does this include that no one can go to South Pole this year and fix ARA 2 - 4 this year? Or what is the assumption?

2021-06-09 15:30 UTC, clark2668 commented
@anelles , thanks--probably not. I'm working on refining the assumptions now.

2021-07-22 08:32 UTC, cg-laser commented
now that the ICRC is over and the plots are final, I think we can merge this one.

2021-07-22 12:47 UTC, clark2668 commented
I think this is mostly good, but a few quick points might help things:

1. Can we converge on having a single `E2_fluxes.py` file? I suspect this means removing `E2_fluxes.py` and `E2_fluxes2.py` and renaming `E2_fluxes3.py` so that it's the single remaining version.
2. Can we remove unnecessary comments from `E2_fluxes3.py`? The HESE 6 years is all commented out for some reason?  And there are lines commented out in some places, e.g. [here](https://github.com/nu-radio/NuRadioMC/blob/improve-limit-plot/NuRadioMC/examples/Sensitivities/E2_fluxes3.py#L175) and [here](https://github.com/nu-radio/NuRadioMC/blob/improve-limit-plot/NuRadioMC/examples/Sensitivities/E2_fluxes3.py#L209).
3. Can we add the Gen2 review array (the one shown in the proceedings) to the repository, either as a CSV file or inline in the file? I think this is important to ensure reproducibility.

2021-07-22 12:51 UTC, clark2668 requested changes
I'll put this here also (so it exists in the review document):

I think this is mostly good, but a few quick points might help things:

- Can we converge on having a single E2_fluxes.py file? I suspect this means removing E2_fluxes.py and E2_fluxes2.py and renaming E2_fluxes3.py so that it's the single remaining version.
- Can we remove unnecessary comments from E2_fluxes3.py? The HESE 6 years is all commented out for some reason? And there are lines commented out in some places. I marked one of them.
- - Can we add the Gen2 review array (the one shown in the proceedings) to the repository, either as a CSV file or inline in the file? I think this is important to ensure reproducibility.

2021-07-22 12:51 UTC, clark2668 commented on NuRadioMC/examples/Sensitivities/E2_fluxes3.py
> +# nu_mu_data[:, 2] = 10 ** nu_mu_data[:, 1] - 10 ** (nu_mu_data[:, 1] - nu_mu_data[:, 2])
It would be good to cleanup commented out lines like this.

2021-11-05 11:05 UTC, clark2668 approved these changes
Approved.

2021-11-05 11:59 UTC, merged