Improve debug output direction fitter
nu-radio/NuRadioMC pull request #549
Opened 2023-07-06 09:40 UTC by cg-laser

improves output of correlation DirectionFitter to calcualate angular differences better. 

Also fixed hardcoded RNO-G specific import

2023-07-07 13:15 UTC, sjoerd-bouma requested changes
See comment regarding the standard deviation - I don't think this is correct right now. Other than that, this looks good to me. Documentation failing is due to the make_docs script, I'll look into that next week as well. Thanks Christian!

2023-07-07 13:15 UTC, sjoerd-bouma commented on NuRadioReco/modules/correlationDirectionFitter.py
> +                std_sim_az = np.angle(np.std(temp_complex_representation.real)+ 1j * np.std(temp_complex_representation.imag))
First line could in principle be simplified (the two means are additive), and I'm not sure the second one is correct - [Wikipedia](https://en.wikipedia.org/wiki/Wrapped_normal_distribution#Moments) backed up my some toy Monte Carlo suggests
```
std_sim_az = np.sqrt(np.log(1/np.mean(temp_complex_representation)**2))
```

2023-07-07 13:15 UTC, sjoerd-bouma commented on NuRadioReco/eventbrowser/dataprovider.py
> +    print("can't import RNO-G root reader")
The dataprovider_root has not yet been updated for the new RNO-G reader, and we already removed the old one, leading to this error. This is already fixed on `rnog_eventbrowser`, I can make a PR next week. But it's probably okay to leave it like this.

2025-02-11 09:50 UTC, fschlueter commented on NuRadioReco/eventbrowser/dataprovider.py
> +    print("can't import RNO-G root reader")
Yes this class does not exist anymore.

2025-02-11 09:51 UTC, fschlueter commented
@cg-laser the requested changes seem minimal. Can we conclude on this PR soon?

2025-02-18 08:43 UTC, cg-laser commented
let's close this PR. It is likely anyway outdated.

2025-02-18 08:43 UTC, closed without merging