Numba ray tracing
nu-radio/NuRadioMC pull request #619
Opened 2024-02-05 13:19 UTC by elariekerboull

PLEASE EDIT AND DELETE THIS TEXT WHEN MAKING A PR.
THIS IS A REMINDER OF WHAT THE PR SHOULD CONTAIN.

Issue being addressed:

Did you remember to: 
* include doc strings in all commits ?
* edit the changelog.txt file describing your changes?

2024-02-05 13:57 UTC, elariekerboull commented
Please don't hesitate to ask for clarifications on some choices if needed.

2024-02-06 15:48 UTC, sjoerd-bouma commented
I don't have time to look at this in detail right now, but I've enabled the tests, and they don't seem to complete without errors yet - can you take a look?
Other than that, this looks really nice, thanks @elariekerboull! I am a little bit apprehensive about building this on a feature in `numba` that is called 'experimental' (jitclass), but I don't know to what extent we should be worried about that. Two more thoughts: 
1) as you mention, compiling the code the first time takes a while - I know for functions the compiled code can be cached, if this is the same for `jitclass`, it would be nice if you could enable this here too
2) it would be good to add a test to the unit tests that tests all three codes (C++, Python and numba)

2024-02-07 20:49 UTC, cg-laser requested changes
Nice work! This will be very useful!

Your testing script does not yet test all relevant functions, as you only calculate the path between two points. The other time critical computation is the attenuation. To do that add something like
```
frequencies = np.linspace(0, 1000, 200) * units.MHz
for iS in range(2):
      attenuation = rays.get_attenuation(iS, frequencies, max_detector_freq=500*units.MHz)
```
to your test script. 
You will probably find that you will also need to optimize the `get_attenuation_along_path` function. 

Here a few thoughts about the implementation: 

It seems that you replicated/copy-pased a few functions to the new helper class. Can we avoid that? It would be much better if you could avoid code duplication. The current implementation is error prone as soon as we want to change anything as we would need to consistently change it in both locations. 

Do you need a class? Or would it be easier to just implement the relevant functions as non-member functions? Then you could even leave them in the original file and you would only need to add a @numba decorator. Maybe then you also don't need the experimental "jitclass" feature? This is just an idea, you probably have better ideas. 
If there is no way around having them in a separate class, maybe the default python implementation could just use these functions(?).

Can you allow turning numba on and off via an argument to the ray_tracing class? Either add a `use_numba` argument (similar to the `use_cpp` argument).

2025-01-10 12:41 UTC, sjoerd-bouma commented
Closing this as merged via #660

2025-01-10 12:41 UTC, closed without merging