Added tolerance to parallel channels
nu-radio/NuRadioMC pull request #634
Opened 2024-02-21 02:28 UTC by rricesmith

Modifications to function get_parallel_channels:
-Fixed bug where it attempted to save differently sized numpy arrays into a single array, causing an error
-Removed repeats of parallel or individual channels from being returned
-Added a tolerance parameter, which allows for there to be deviation in parallel channels and still be counted as parallel. Necessary for detector descriptions of real experiments whose antennas may deviate by a few degrees.

2024-02-22 20:25 UTC, cg-laser requested changes
it is an improvement but not yet doing what it should. 

E.g. if one angle is 0.1deg and the other 359.9, the difference is 359.8. Or in other words, the periodicity needs to be taken into account. 

The other thing is the restriction to 180deg interval for the rotation angle. Antennas can be anti-parallel which makes a difference (the trace is inverted, i.e. multiplied with -1). I would make it optional to return also anti-parallel channels or not.

2024-02-29 21:14 UTC, rricesmith commented
Updated to account for the periodicity of the angles. Also included an option for anti-parallel.

Example using a sample detector, with 0-3 standard downward LPDAs, 4-6 are standard upward with the 4th LPDA removed, and ch7 is a bicone.:
tol=1deg: [array([7]), array([0, 2]), array([1, 3]), array([4, 6]), array([5])]
tol=91deg: [array([7]), array([0, 2]), array([0, 1, 2, 3]), array([4, 6]), array([4, 5, 6])]

There are repeated channels still in some cases. This existed in the old version of this function, and I believe causes no issues with modules that use this. It might be preferred, as I believe this happens because we have 4 axis of rotation, and its possible that given a set of 3 orientations (a, b & c), that [a,b] can be parallel within tolerance, and [b, c] can be, but [a, c] cannot be.

2024-03-01 19:55 UTC, cg-laser commented on NuRadioReco/detector/detector_base.py
> +                return np.abs(hp.get_normalized_angle(a - b, interval=np.deg2rad([0, 180])))
I think the intervals need to be [-90, 90] and [-180,180].

2025-02-11 09:47 UTC, fschlueter commented
I created a branch `parallel-channels` with the changes introduced here + some modifications + the suggestion by Christian. I will close this PR. Feel free to reopen it or continue developing this feature with the new branch. (I had to make a new branch because this PR uses a fork).

2025-02-11 09:47 UTC, closed without merging